[platformio]
default_envs = ota_upload

[env]
platform = espressif32
framework = arduino
board = freenove_esp32_wrover

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -O3                                     ; Máxima optimización de velocidad en C++
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D CONFIG_ARDUINO_RUNNING_CORE=1        ; Core 1 para Arduino / Motores / Servos
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=0      ; Core 0 para la pila TCP / WebSockets
    -D CONFIG_ASYNC_TCP_USE_WDT=0           ; Desactiva WDT en TCP para evitar reinicios por alta carga
    -D CORE_DEBUG_LEVEL=0                   ; Desactiva logs para ahorra ciclos de CPU y RAM

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

; PSRAM a máxima frecuencia (80MHz)
board_build.f_psram = 80000000L 

board_build.partitions = min_spiffs.csv

lib_deps = 
    xreef/PCF8574 library @ ^2.3.7
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2



[env:serial_upload]
upload_port = COM8
monitor_port = COM8

[env:ota_upload]
upload_protocol = espota
upload_port = 192.168.0.202